---
title: "Cayendo en las redes de Venecia"
author: "JJ Merelo"
date: "`r Sys.Date()`"
output: html_document
abstract: |
    La República de Venecia se benefició de una comprensión intuitiva del poder
    de las redes para crear su imperio basado en el comercio marítimo. En este
    trabajo explicamos diferentes conclusiones que se han alcanzado estudiando
    diferentes conjuntos de datos de redes comerciales, y también redes matrimoniales.
bibliography: venice.bib
---

> Esta página ha sido generada automáticamente a partir del [fuente](https://github.com/JJ/redes-venecia/blob/main/redes-venecia.Rmd), que tiene una licencia libre y, como tal, puedes examinarlo para ver cómo se analizan los datos y se obtienen los resultados y los gráficos, y por supuesto copiar, modificar y republicar si lo deseas, siempre que se respete la [licencia](https://github.com/JJ/redes-venecia/blob/main/LICENSE).

```{r setup,echo=FALSE,message=FALSE}
source("R/utils.R")
```

Durante sus más de mil años de existencia, la república de Venecia fue gobernada
por `r length(data.doges$Years)` dogos. La estabilidad de la forma de estado y su prosperidad económica en la época de apogeo tiene pocos paralelismos en la historia medieval e incluso moderna. Y esta estabilidad se debe, en gran parte, a un entendimiento y consiguiente control de las redes y sus comportamientos emergentes. La prosperidad de Venecia se debió al control de las redes comerciales en el Mediterráneo oriental y más allá; pero como comportamiento emergente en esas redes comerciales apareció una red social basada en relaciones económicas. De esa red de relaciones comerciales emergió una clase noble que cerró el acceso al poder a otras clases emergentes, pero, a su vez, esa clase noble creó una verdadera red matrimonial autoorganizada que a la vez impedía la emergencia de una sola familia dominante y el acceso de otras clases no nobles al poder. En la periferia de esas redes había muchas otras que se apoyaban entre sí, pero sobre todo soportaban el poder de la red social de los nobles que gobernaban la ciudad: una red de innovación tecnológica, redes urbanas [@psarra2018role] y redes de intercambio de información, y las redes comerciales que siguieron teniendo importancia incluso después de la graduación a redes sociales.

El poder de Venecia, mientras duró, atestigua el poder de las redes y afortunadamente, la estabilidad del mismo y su obsesión con la información dejó suficientes datos como para poder estudiarlo. En este informe nos fijaremos principalmente en dos puntos neurálgicos de la red urbana de Venecia: Rialto y su preponderancia comercial, y la Piazza San Marco y el Palacio de los Dogos y su papel político, analizando dos redes sociales de las cuales tenemos datos: la red de la *colleganza* o alianzas comerciales para fletar galeras, y la red matrimonial de los dogos, o presidentes vitalicios de la república. 

## Ciencia abierta

Este trabajo se ha llevado a cabo con los principios de ciencia
abierta y ciencia ágil [@mereloguervos2022agile]. Está disponible en
[el repositorio de GitHub
`https://github.com/JJ/redes-venecia`](https://github.com/JJ/redes-venecia).



## Reconocimientos

Es un material que acompaña al poster "Cayendo en las redes de Venecia" que se
presentará en el CITICCoffee de mayo de 2023.

## Bibliografía

