name: "Generate web page"

on:
  push:
    paths:
      - '*.Rmd'
      - .github/workflows/generate.yml

jobs:
  generate-document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: Install latex
        run: sudo apt-get install -y texlive-latex-recommended
      - name: Generate file
        run: bin/rmd-render.R redes-venecia.Rmd

      - name: Check in result
        run: |
          if [ -n "$(git status -s)" ]; then
              bin/commit-push.sh "Re-generated HTML" && git push
          else
              echo "ℹ No new files"
          fi
